In [ ]:
#Numpy once again, Never out of the fight, never affected by the fight.
# I am here to study and listen to the class, give my best, less GO !!

In [5]:
import numpy as np 

In [16]:
n1 = np.array([[1,2,3,4,5],[11,12,13,14,15]]) #basically we can also do this on a 2-D array !
n2 = np.array([10,20,30,40,50])

In [17]:
print(n1+3) #this is basically scalar and vector addition, element-wise +3

[[ 4  5  6  7  8]
 [14 15 16 17 18]]


In [18]:
print(n1*3)

[[ 3  6  9 12 15]
 [33 36 39 42 45]]


In [19]:
print(n1)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [20]:
print(n1**3)

[[   1    8   27   64  125]
 [1331 1728 2197 2744 3375]]


In [24]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[10,20,30],[40,50,60]])

In [30]:
print(n1+n2)

[[11 22 33]
 [44 55 66]]


In [29]:
print(n1-n2)

[[ -9 -18 -27]
 [-36 -45 -54]]


In [28]:
print(n1*n2)

[[ 10  40  90]
 [160 250 360]]


In [31]:
print(n1*10+n2)

[[ 20  40  60]
 [ 80 100 120]]


In [32]:
n1 = np.arange(1,21)

In [33]:
print(n1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [34]:
n2 = np.arange(1,101)
print(n2)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [36]:
newarr = n2.reshape(10, 10)

In [37]:
print(newarr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [50]:
print(newarr[[0,1,2],[1,1,1]]) #fancy way of indexing, I firt chose the arr, then I further closed in on the index.

[ 2 12 22]


In [51]:
a,b = [1,2]

In [54]:
newarr[[True, False, False, True, False, True, False, True, False, True]] #so basically only those arrays with tru printed

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [57]:
n2 > 10 #Impotant concept, known as filtering.

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [60]:
n2[n2 > 10] #the only true values will be printed here.

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [69]:
arr = np.array([[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]]) #axis = 0,1,2

In [70]:
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[10 20]
  [30 40]
  [50 60]]]


In [75]:
print(arr.sum(axis = 0))

[[11 22]
 [33 44]
 [55 66]]


In [78]:
print(arr.sum(axis = 1)) #corresponds to 1-D arrays

[[  9  12]
 [ 90 120]]


In [84]:
print(arr.sum(axis = 2)) #corresponding to the columns

[[  3   7  11]
 [ 30  70 110]]


In [87]:
print(arr.max(axis = 2)) #brings the maximum value from the columns

[[ 2  4  6]
 [20 40 60]]


In [88]:
n = np.array([False, True, False])


In [90]:
n1 = np.arange(1,11)

In [91]:
for t in np.ndenumerate(n1):
    print(t)

((0,), np.int64(1))
((1,), np.int64(2))
((2,), np.int64(3))
((3,), np.int64(4))
((4,), np.int64(5))
((5,), np.int64(6))
((6,), np.int64(7))
((7,), np.int64(8))
((8,), np.int64(9))
((9,), np.int64(10))


In [92]:
n1 = np.array([1,2,3])
n2 = np.array([10,20,30])

In [95]:
np.vstack((n1,n2)) #stack them vertically

array([[ 1,  2,  3],
       [10, 20, 30]])

In [96]:
np.hstack((n1,n2)) #stack them horizontally

array([ 1,  2,  3, 10, 20, 30])

In [99]:
np.stack((n1,n2),axis = 1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [103]:
print(np.hsplit(n1,3))

[array([1]), array([2]), array([3])]


In [104]:
#Broadcasting in numpyBroadcasting is a 
#powerful feature in NumPy that allows operations between arrays
#of different shapes without making unnecessary copies of data.

In [105]:
n1 = np.arange(1,13).reshape(4,3)

In [108]:
print(n1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [107]:
print(np.array([10,20,30]) + n1)

[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [110]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b) #this is a classic example of broadcasting.


[[11 22 33]
 [14 25 36]]


In [111]:
import os
os.getcwd()

'/Users/kshitijsharma/Desktop/CB-ML-AI/Class-13'

In [121]:
file_path = '/Users/kshitijsharma/Desktop/populations.txt'


In [122]:
with open(file_path, 'r') as f:
    data = f.read()
    print(data)

# year	hare	lynx	carrot
1900	30e3	4e3	48300
1901	47.2e3	6.1e3	48200
1902	70.2e3	9.8e3	41500
1903	77.4e3	35.2e3	38200
1904	36.3e3	59.4e3	40600
1905	20.6e3	41.7e3	39800
1906	18.1e3	19e3	38600
1907	21.4e3	13e3	42300
1908	22e3	8.3e3	44500
1909	25.4e3	9.1e3	42100
1910	27.1e3	7.4e3	46000
1911	40.3e3	8e3	46800
1912	57e3	12.3e3	43800
1913	76.6e3	19.5e3	40900
1914	52.3e3	45.7e3	39400
1915	19.5e3	51.1e3	39000
1916	11.2e3	29.7e3	36700
1917	7.6e3	15.8e3	41800
1918	14.6e3	9.7e3	43300
1919	16.2e3	10.1e3	41300
1920	24.7e3	8.6e3	47300



In [129]:
pop = np.loadtxt('/Users/kshitijsharma/Desktop/populations.txt')


In [131]:
print(pop)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [132]:
pop.max(axis = 0)

array([ 1920., 77400., 59400., 48300.])

In [133]:
pop[:,0][pop.argmax(axis = 0)][1:]

array([1903., 1904., 1900.])

In [134]:
n1 = np.arange(1,13).reshape(3,4)

In [135]:
n1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])