In [ ]:
#Never out of the fight, Never affected by the fight.


In [3]:
import numpy as np 


In [7]:
a = np.array([10 ,20 , 30, 40, 50])

In [8]:
print(a) 

[10 20 30 40 50]


In [10]:
a.shape

(5,)

In [12]:
arr = np.array([[10, 20, 30, 40, 50], [1, 2, 3, 4, 5], [11, 12, 13, 14, 15]])

In [16]:
arr.shape #Gives us the shape here, 3 rows and 5 columns

(3, 5)

In [17]:
print(arr) # so basically a matix was formed with 3 rows and 5 columns,

[[10 20 30 40 50]
 [ 1  2  3  4  5]
 [11 12 13 14 15]]


In [18]:
arr[0] # Gives us the first array Obviously

array([10, 20, 30, 40, 50])

In [19]:
arr[1] # Gives us the second array, obviously.

array([1, 2, 3, 4, 5])

In [23]:
arr[2] # Gives us the third array, obviously.

array([11, 12, 13, 14, 15])

In [24]:
arr[0][0] # basically to access the first element of the 2-D matrix

np.int64(10)

In [27]:
mat = np.ones([3,3])

In [33]:
arr_int = arr.astype(int) #basically converting the whole stuff to integer.
print("\nArray after converting to int:")
print(arr_int)


Array after converting to int:
[[10 20 30 40 50]
 [ 1  2  3  4  5]
 [11 12 13 14 15]]


In [44]:
mat_int  = mat.astype(int) #basically converting the whole stuff to integer.
print(mat_int)
print()
print(mat.astype(int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
line_arr  = np.linspace(0, 10, num=5)
print(line_arr)


[ 0.   2.5  5.   7.5 10. ]


In [42]:
line_arr  = np.linspace(0, 100, num=5) #basically to print out equispaced arrays.
print(line_arr.astype(int))

[  0  25  50  75 100]


In [53]:
x = np.ones([3,3], dtype= int)

In [54]:
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [55]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])


In [61]:
Sorted_array = np.sort(arr)

In [62]:
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [63]:
print(Sorted_array)

[1 2 3 4 5 6 7 8]


In [65]:
a = np.array( [10, 20, 30, 40, 50, 60, 70] )
b = np.array( [100, 200, 300, 400, 500, 600, 700])

In [67]:
conc = np.concatenate((a,b))

In [68]:
print(conc)

[ 10  20  30  40  50  60  70 100 200 300 400 500 600 700]


In [70]:
print(np.concatenate((a,b)))

[ 10  20  30  40  50  60  70 100 200 300 400 500 600 700]


In [71]:
add = a + b ; 

In [72]:
print(add) 

[110 220 330 440 550 660 770]


In [73]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [77]:
xy = np.concatenate((x, y), axis=0)
print(xy)

[[1 2]
 [3 4]
 [5 6]]


In [79]:
a = np.arange(6) #Basically we are trying to reshape an array here !!
print(a)
print()
b = a.reshape(3, 2) # We are trying to reshape the array here, using a.reshape()
print(b)

[0 1 2 3 4 5]

[[0 1]
 [2 3]
 [4 5]]
