In [ ]:
#Class : 12, Never out of the fight, never affected by the fight.

In [6]:
import numpy as np #it is bascially a library for array manuplations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5 7 9]

[5 7 9]


In [7]:
# basically helps in doing scientific calculations in python.

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)        # [4 10 18]
print(a ** 2)       # [1 4 9]
print(b ** 2) 

[ 4 10 18]
[1 4 9]
[16 25 36]


In [9]:
np.eye(3)   

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.ones((3, 3))    #3*3 matrix with ones  

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:

a = np.array([10, 20, 30, 40])
a[1:3]

array([20, 30])

In [16]:
np.zeros((2, 3))     # 2x3 matrix of zeros
np.ones((3, 2))      # 3x2 matrix of ones
np.eye(3)            # 3x3 Identity matrix
np.arange(0, 10, 2)  # [0 2 4 6 8]
np.linspace(0, 1, 5) # [0.   0.25 0.5  0.75 1.]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.zeros((2, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
import numpy as np
print(np.__version__)


2.2.3


In [61]:
l1 = [1,2,3,4]
l2 = [[1,2],[3,4],[5,6]] #Numpy is considering the list as an object here.
l3 = [[[10, 20], [30, 40]], [[1, 2], [3, 4]]]



In [68]:
n1 = np.array(l1)
n2 = np.array(l2, dtype  = 'object')
n3 = np.array(l3)

In [77]:
type(n1)
type(n2)
type(n2)

numpy.ndarray

In [78]:
print(n1)

[1 2 3 4]


In [79]:
n1.shape #basically gives us the shape.

(4,)

In [80]:
n2.shape

(3, 2)

In [73]:
n3.shape

(2, 2, 2)

In [75]:
print(l1[2] ,n1[2])

3 3


In [81]:
print(l3[0][1][0],n3[0,1,0])

30 30


In [82]:
n1.dtype

dtype('int64')

In [84]:
n3.dtype

dtype('int64')

In [88]:
narr = np.arange(1,11)

In [89]:
print(narr)

[ 1  2  3  4  5  6  7  8  9 10]


In [91]:
np.linspace(1,10,5) #2.25 in between [1,10]

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [99]:
np.ones(shape = (3,2,3) , dtype='int')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [102]:
a = np.array([1, 2, 3], dtype='int')
print(a)        # [1. 2. 3.]
print(a.dtype)  # int64

[1 2 3]
int64


In [104]:
np.ones(shape = (5,2) , dtype = 'int')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [106]:
narr = np.arange(1,101)

In [108]:
narr = narr.reshape(10,10)

In [109]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [110]:
np.random.randn(3,2,2)

array([[[-0.35082103,  0.87689349],
        [-1.65026394,  0.71456948]],

       [[-0.00611269, -0.43579516],
        [-0.3070612 ,  1.13938521]],

       [[-0.17298134,  0.8056248 ],
        [ 1.1278695 , -0.4852198 ]]])

In [112]:
np.random.random(size=(5,2))

array([[0.21619621, 0.82983575],
       [0.61225883, 0.22321155],
       [0.4809446 , 0.48481602],
       [0.48380833, 0.56070533],
       [0.8835038 , 0.76160669]])

In [114]:
np.random.randint(1,101,size=(5,2))

array([[98, 72],
       [45, 10],
       [70, 44],
       [35, 19],
       [43, 39]])

In [117]:
np.random.choice(np.array([1,2,3,4,5,6,7,8,9]),size=(5,),replace= True,p = [0,0,0,0,0.1,0.2,0.3,0.4,0])

array([6, 7, 5, 7, 8])

In [122]:
narr = np.arange(1,101)
np.random.shuffle(narr)#basicaly shuffling will happen !!

In [123]:
narr

array([ 19,   5,  95,  26,  35,  42,  75,  45,  94,   4,  87,  71,  56,
        83,  15,  23,  14,  85,  90,  20,  93,   1,  91,  30,   9,  96,
        52,   3,  47,  29,  88,  63,  18,  76,  80,  69,  64,  22,  58,
        66,  17,  51,  82,  33,  72,  53,  38,  50,  44,  59,  49,  92,
        97,  25,  39,  12,  55,   7,  65,  67,  11,  41,  10,  99,  34,
        81,  46,  28,  24,  86,  21,  57,  60,  32,  16,   8,   6,   2,
        98,  73,  61,  79,  84,  89,  31,  48,  40,  27,  70,  54,  13,
        62,  77,  37,  68, 100,  36,  78,  74,  43])

In [126]:

narr.reshape((-1,))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [134]:
narr[1] = 350 #narr[1,4,4] = 350 

In [135]:
narr

array([  1, 350,   3,   4, 350,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [136]:
narr = np.arange(1,101).reshape((10,10))

In [137]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])